# -*- coding: utf-8 -*-
"""Machine Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4F918eB_uAsdszVhRJ0pxWW0v6YcSx5
"""

# A. Agriculture
# Project 4 : Prediction of Agriculture Crop Production in India.

# ------------------- Import Libraries -------------------
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor

# ------------------- Create Dataset -------------------
data = [
    ["ARHAR","Uttar Pradesh",9794.05,23076.74,1941.55,9.83,"Total Foodgrains",
     158.8,168.6,171.3,159.4,178.9,
     128.5,128.8,127.6,126.0,131.7,
     123.6,130.9,134.3,126.5,135.9,
     "Paddy","Chinsurah Rice (IET 19140)","Medium",
     "Zone1","Agricultural Production","Annual","Ton",
     *([np.nan]*12),
     198.36,208.60,217.28,230.77,234.46,
     218.10,244.49,259.28,257.13,264.38
    ],

    ["ARHAR","Karnataka",10593.15,16528.68,2172.46,7.47,"Rice",
     200.8,207.9,213.3,191.6,206.4,
     168.5,168.9,175.1,161.2,164.8,
     119.2,123.1,121.8,118.9,125.2,
     "Paddy","CNI 383-5-11","Low",
     "Zone2","Agricultural Production","Annual","Ton",
     *([np.nan]*12),
     103.30,109.87,110.57,120.95,118.13,
     103.95,120.85,131.27,128.07,129.36
    ]
]

columns = [
    "Crop","State","Cost_A2_FL","Cost_C2","Cost_Production_C2","Yield","Category",
    "Production_2006_07","Production_2007_08","Production_2008_09","Production_2009_10","Production_2010_11",
    "Area_2006_07","Area_2007_08","Area_2008_09","Area_2009_10","Area_2010_11",
    "Yield_2006_07","Yield_2007_08","Yield_2008_09","Yield_2009_10","Yield_2010_11",
    "Crop_2","Variety","Season","Recommended_Zone",
    "Particulars","Frequency","Unit",
    "1993","1994","1995","1996","1997","1998",
    "1999","2000","2001","2002","2003","2004",
    "2005","2006","2007","2008","2009","2010",
    "2011","2012","2013","2014"
]

df = pd.DataFrame(data, columns=columns)

# ------------------- EDA -------------------
print("Dataset Preview:\n", df.head())
print("\nInfo:\n")
print(df.info())

# ------------------- Data Cleaning -------------------

# Drop columns with all NaN (1993–2004)
df.drop(columns=[str(year) for year in range(1993, 2005)], inplace=True)

# Drop unnecessary text-heavy columns
df.drop(["Crop_2", "Variety", "Recommended_Zone", "Particulars"], axis=1, inplace=True)

# Fill remaining missing values
df.fillna(0, inplace=True)

# ------------------- Encoding -------------------
categorical_cols = ['Crop','State','Category','Season','Frequency','Unit']

le = LabelEncoder()
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

# ------------------- Feature Selection -------------------
y = df["Production_2010_11"]

X = df.drop(["Production_2010_11"], axis=1)

# Optional: Reduce features (recommended for tiny dataset)
X = X[[
    "Cost_A2_FL",
    "Cost_C2",
    "Cost_Production_C2",
    "Yield",
    "Production_2006_07",
    "Production_2007_08",
    "Production_2008_09",
    "Production_2009_10"
]]

# ------------------- Model Training -------------------
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X, y)

# ------------------- Prediction -------------------
y_pred = model.predict(X)

# ------------------- Output -------------------
print("\nActual Values:", y.values)
print("Predicted Values:", y_pred)

# ------------------- Feature Importance -------------------
importance = pd.Series(model.feature_importances_, index=X.columns)
print("\nFeature Importance:\n", importance.sort_values(ascending=False))

# ------------------- Visualization -------------------

# 1. Cost Comparison
plt.figure(figsize=(8,5))
df[['Cost_A2_FL','Cost_C2','Cost_Production_C2']].plot(kind='bar')
plt.title("Cost Comparison")
plt.xlabel("Index")
plt.ylabel("Cost")
plt.xticks(rotation=0)
plt.legend()
plt.show()


# 2. Yield Comparison by State
plt.figure(figsize=(6,4))
sns.barplot(x='State', y='Yield', data=df)
plt.title("Yield by State")
plt.show()


# 3. Production Trend (2006–2010)
years = ['Production_2006_07','Production_2007_08','Production_2008_09',
         'Production_2009_10','Production_2010_11']

plt.figure(figsize=(8,5))
for i in range(len(df)):
    plt.plot(years, df.loc[i, years], marker='o', label=f"Sample {i}")

plt.title("Production Trend")
plt.xlabel("Year")
plt.ylabel("Production")
plt.legend()
plt.xticks(rotation=45)
plt.show()


# 4. Correlation Heatmap
plt.figure(figsize=(10,6))
sns.heatmap(df.select_dtypes(include=np.number).corr(), annot=True, cmap='coolwarm')
plt.title("Feature Correlation Heatmap")
plt.show()


# 5. Feature Importance (after model training)
importance = pd.Series(model.feature_importances_, index=X.columns)

plt.figure(figsize=(8,5))
importance.sort_values().plot(kind='barh')
plt.title("Feature Importance")
plt.show()

# A. Agriculture
# Project 5 : Crop and Weed Detection.

# Install YOLO
   #!pip install ultralytics

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Create data.yaml file
with open('data.yaml', 'w') as f:
    f.write("""
path: /content/drive/MyDrive/Project5_Ag_Crop_and_weed
train: images/train
val: images/val

names:
  0: crop
  1: weed
""")

# Check dataset
import os

train_path = "/content/drive/MyDrive/Project5_Ag_Crop_and_weed/images/train"

if os.path.exists(train_path):
    print("✅ Dataset found")
    print("Total training images:", len(os.listdir(train_path)))
else:
    print(" Dataset NOT found. Check folder name.")

# Train YOLO model
from ultralytics import YOLO

model = YOLO('yolov8n.pt')

model.train(
    data='data.yaml',
    epochs=50,
    imgsz=512
)

# Prediction
results = model.predict(
    source='/content/drive/MyDrive/Project5_Ag_Crop_and_weed/images/val',
    save=True
)

# Show output
from IPython.display import Image, display
import glob

output_images = glob.glob('runs/detect/predict/*.jpg')

if output_images:
    display(Image(filename=output_images[0]))
else:
    print(" No output images found")

#Predictive maintenance
#Project 6: Predict the number of remaining operational cycles before failure for Turbofan engine

'''Data set Link:
https://drive.google.com/file/d/1dgWM0KKOnoN9kVObbA-GahsgXPJBCT4c/view?usp=sharing'''

# STEP 1: Install & Import
   #!pip install pandas numpy scikit-learn matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import zipfile
import os

from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# STEP 2: Extract ZIP
zip_path = "/content/drive/MyDrive/data/Project6_Pdm_Predict the number of remaining operational cycles before failure for Turbofan engine.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/drive/MyDrive/data")

print("Files extracted:", os.listdir("/content/drive/MyDrive/data"))

# STEP 3: Define Columns
cols = ['unit', 'cycle'] + [f'op{i}' for i in range(1,4)] + [f's{i}' for i in range(1,22)]

# STEP 4: Load Data
train = pd.read_csv('/content/drive/MyDrive/data/train_FD001.txt', sep=' ', header=None)
train = train.dropna(axis=1)
train.columns = cols

test = pd.read_csv('/content/drive/MyDrive/data/test_FD001.txt', sep=' ', header=None)
test = test.dropna(axis=1)
test.columns = cols

print("Train shape:", train.shape)
print("Test shape:", test.shape)

# STEP 5: Create RUL (Target)
rul = train.groupby('unit')['cycle'].max().reset_index()
rul.columns = ['unit', 'max_cycle']

train = train.merge(rul, on='unit')
train['RUL'] = train['max_cycle'] - train['cycle']
train.drop(['max_cycle'], axis=1, inplace=True)

# STEP 6: Normalize Data
scaler = MinMaxScaler()
features = train.columns.drop(['unit', 'cycle', 'RUL'])

train[features] = scaler.fit_transform(train[features])
test[features] = scaler.transform(test[features])

# STEP 7: Train Model
X = train[features]
y = train['RUL']

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X, y)

# STEP 8: Evaluate Model
train_pred = model.predict(X)
rmse = np.sqrt(mean_squared_error(y, train_pred))

print("\nModel Evaluation:")
print("RMSE:", rmse)

# STEP 9: Predict on Test Data
pred = model.predict(test[features])

print("\nSample Predictions (RUL):")
print(pred[:10])

# STEP 10: Visualization
plt.figure()
plt.plot(y.values[:100], label='Actual RUL')
plt.plot(train_pred[:100], label='Predicted RUL')
plt.legend()
plt.title("Actual vs Predicted RUL (First 100)")
plt.xlabel("Samples")
plt.ylabel("RUL")
plt.show()


#Project 7: Predict life time of a bearing in manufacturing industry
#Data set Link:
#https://drive.google.com/file/d/12rV9AhpqbMivYCu4WVM7DhXpO1aO98k_/view?usp=sharing

import os
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error


# Feature Extraction Function
def extract_features(signal):
    features = []

    features.append(np.mean(signal))
    features.append(np.std(signal))
    features.append(np.max(signal))
    features.append(np.min(signal))
    features.append(np.ptp(signal))
    features.append(np.sqrt(np.mean(signal**2)))  # RMS
    features.append(np.mean(np.abs(signal)))
    features.append(np.mean(signal**2))

    return features


# Load Dataset
def load_data(data_path):
    files = sorted(os.listdir(data_path))
    X = []

    print(f"Processing {len(files)} files...")

    for file in tqdm(files):
        file_path = os.path.join(data_path, file)

        try:
            data = np.loadtxt(file_path)
            signal = data[:, 0]  # Using first channel

            features = extract_features(signal)
            X.append(features)

        except:
            continue

    return np.array(X)



# Create RUL Labels

def create_rul_labels(num_samples):
    return np.arange(num_samples, 0, -1)



# Main Pipeline for 1st_test
def main():
    data_path = "/content/drive/MyDrive/data2/1st_test"   # change if needed

    X = load_data(data_path)
    print("Feature Shape:", X.shape)

    y = create_rul_labels(len(X))

    scaler = MinMaxScaler()
    X_scaled = scaler.fit_transform(X)

    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=0.2, shuffle=False
    )

    model = RandomForestRegressor(n_estimators=100)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    print("MAE:", mae)

    # Plot
    plt.figure(figsize=(10,5))
    plt.plot(y_test, label="Actual RUL")
    plt.plot(y_pred, label="Predicted RUL")
    plt.legend()
    plt.title("RUL Prediction")
    plt.show()

if __name__ == '__main__':
  main()

# Main Pipeline for 2nd_test
def main():
    data_path = "/content/drive/MyDrive/data2/2nd_test"   # change if needed

    X = load_data(data_path)
    print("Feature Shape:", X.shape)

    y = create_rul_labels(len(X))

    scaler = MinMaxScaler()
    X_scaled = scaler.fit_transform(X)

    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=0.2, shuffle=False
    )

    model = RandomForestRegressor(n_estimators=100)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    print("MAE:", mae)

    # Plot
    plt.figure(figsize=(10,5))
    plt.plot(y_test, label="Actual RUL")
    plt.plot(y_pred, label="Predicted RUL")
    plt.legend()
    plt.title("RUL Prediction")
    plt.show()

if __name__ == '__main__':
  main()


  #Project 8: Predictive maintenance of Gearbox using vibration sensors

'''Predictive maintenance allows manufacturers to lower maintenance costs, extend equipment life, reduce downtime and improve production quality by addressing problems before they cause equipment failures.
Gearbox Fault Diagnosis Data set include the vibration dataset recorded by using SpectraQuest’s Gearbox Fault Diagnostics Simulator. Dataset has been recorded with the help of 4 vibration sensors placed in four different direction. Data set has been recorded under variation of load from '0' to '90' percent. Data set has been recorded in two different scenario:
1) Healthy condition and
2) Broken Tooth Condition
Data set Link:
https://drive.google.com/file/d/1nNNnjMPntlo5X0t_cif7cmlJhikCyWyP/view?usp=sharing'''


# Project 8: Gearbox Predictive Maintenance

# STEP 1: Import Libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# STEP 2: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# STEP 3: Dataset Path
data_path = "/content/drive/MyDrive/data3/gearbox_dataset"

print("Folders inside dataset:", os.listdir(data_path))

# STEP 4: Feature Extraction
def extract_features(signal):
    return [
        np.mean(signal),
        np.std(signal),
        np.max(signal),
        np.min(signal),
        np.median(signal),
        np.percentile(signal, 25),
        np.percentile(signal, 75),
        np.sqrt(np.mean(signal**2))  # RMS
    ]

# STEP 5: Load Dataset

X = []
y = []

conditions = ["Healthy Data", "BrokenToothData"]

for label, condition in enumerate(conditions):
    folder = os.path.join(data_path, condition)
    print(f"\nProcessing: {condition}")

    for file in tqdm(os.listdir(folder)):

        if file.endswith(".txt"):
            file_path = os.path.join(folder, file)

            try:
                # ✅ Read raw lines
                with open(file_path, 'r') as f:
                    lines = f.readlines()

                data = []

                for line in lines:
                    # split by space/tab
                    values = line.strip().split()

                    # convert to float if possible
                    row = []
                    for v in values:
                        try:
                            row.append(float(v))
                        except:
                            pass

                    if len(row) > 0:
                        data.append(row)

                if len(data) == 0:
                    print("Skipped (no numeric data):", file)
                    continue

                df = pd.DataFrame(data)

                # Extract features
                for col in df.columns:
                    signal = df[col].values

                    if len(signal) == 0:
                        continue

                    features = extract_features(signal)

                    X.append(features)
                    y.append(label)

            except Exception as e:
                print("Error in file:", file, e)

# Convert to numpy
X = np.array(X)
y = np.array(y)

print("\nDataset shape:", X.shape)


# STEP 6: Check if data loaded
if len(X) == 0:
    raise ValueError("❌ No data loaded. Check file format!")

# STEP 7: Normalize
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

# STEP 8: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# STEP 9: Train Model
model = RandomForestClassifier(n_estimators=50, random_state=42)
model.fit(X_train, y_train)

# STEP 10: Prediction
y_pred = model.predict(X_test)

# STEP 11: Evaluation
print("\nAccuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# STEP 12: Feature Importance
plt.figure()
plt.bar(range(len(model.feature_importances_)), model.feature_importances_)
plt.title("Feature Importance")
plt.xlabel("Feature Index")
plt.ylabel("Importance")
plt.show()

# C. Smart city
# Project 9: Forecasting of Smart city traffic patterns
# Data set Link:
# https://drive.google.com/file/d/1y61cDyuO9Zrp1fSchWcAmCxk0B6SMx7X/view?usp=sharing

# STEP 1: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_absolute_error, mean_squared_error
from statsmodels.tsa.arima.model import ARIMA
import warnings
warnings.filterwarnings('ignore')

# STEP 2: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# STEP 3: Load TRAIN & TEST Data
train_path = '/content/drive/MyDrive/data4/train_aWnotuB.csv'
test_path  = '/content/drive/MyDrive/data4/test_BdBKkAj.csv'

train_df = pd.read_csv(train_path)
test_df  = pd.read_csv(test_path)

print("Train Data Loaded")
print(train_df.head())

print("\nTest Data Loaded")
print(test_df.head())

# STEP 4: Preprocessing
    # Convert DateTime
train_df['DateTime'] = pd.to_datetime(train_df['DateTime'])
test_df['DateTime']  = pd.to_datetime(test_df['DateTime'])

    # Sort
train_df = train_df.sort_values('DateTime')
test_df  = test_df.sort_values('DateTime')

    # Feature Engineering
for df in [train_df, test_df]:
    df['year'] = df['DateTime'].dt.year
    df['month'] = df['DateTime'].dt.month
    df['day'] = df['DateTime'].dt.day
    df['hour'] = df['DateTime'].dt.hour
    df['day_of_week'] = df['DateTime'].dt.dayofweek

    # Fill missing
train_df.fillna(method='ffill', inplace=True)
test_df.fillna(method='ffill', inplace=True)

# STEP 5: Visualization (Train Data)
plt.figure(figsize=(12,5))
sns.lineplot(data=train_df, x='DateTime', y='Vehicles', hue='Junction')
plt.title("Traffic Pattern (Train Data)")
plt.show()

# STEP 6: Model for Each Junction
predictions = []

for junc in train_df['Junction'].unique():

    print(f"\nProcessing Junction {junc}")

    # Filter data
    train_j = train_df[train_df['Junction'] == junc].copy()
    test_j  = test_df[test_df['Junction'] == junc].copy()

    # Set index
    train_j.set_index('DateTime', inplace=True)

    # Time series
    ts = train_j['Vehicles'].resample('H').mean()
    ts.fillna(method='ffill', inplace=True)

    # Build ARIMA model
    model = ARIMA(ts, order=(5,1,0))
    model_fit = model.fit()

    # Forecast for test length
    forecast = model_fit.forecast(steps=len(test_j))

    # Save predictions
    test_j['Vehicles_Predicted'] = forecast.values
    predictions.append(test_j)
# STEP 7: Combine All Predictions
final_df = pd.concat(predictions)

print("\nFinal Predictions:")
print(final_df.head())

# STEP 8: Save Output
output_path = '/content/drive/MyDrive/data4/traffic_predictions.csv'
final_df.to_csv(output_path, index=False)

print("\n Predictions saved to Drive:", output_path)

# STEP 9: Visualization (Example Junction)
j1 = final_df[final_df['Junction'] == 1]

plt.figure(figsize=(10,5))
plt.plot(j1['DateTime'], j1['Vehicles_Predicted'], label='Predicted')
plt.legend()
plt.title("Predicted Traffic - Junction 1")
plt.show()

# DONE
print("\n Smart City Traffic Forecasting Completed!")

# Industrial Manufacturing and Production
# Project 10: Quality Prediction in a Mining Process
''' Data set Link:
 https://drive.google.com/file/d/1N80d8eTDAf1JMQXGQbHDAUaMGRyA8QG3/view?usp=sharing'''

# STEP 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# STEP 2: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error
from sklearn.ensemble import RandomForestRegressor

# STEP 3: File Paths
data10_path = "/content/drive/MyDrive/Colab Notebooks/data5/MiningProcess_Flotation_Plant_Database.csv"
data11_path = "/content/drive/MyDrive/Colab Notebooks/data6/continuous_factory_process.csv"

# STEP 4: Safe Loader
def load_data(path, name):
    print(f"\nLoading {name}...")
    df = pd.read_csv(path, engine='python', on_bad_lines='skip')
    print(f"{name} Shape:", df.shape)
    return df

df10 = load_data(data10_path, "Mining Dataset")
df11 = load_data(data11_path, "Manufacturing Dataset")

# PROJECT 10: Mining
print("\n===== PROJECT 10: Mining =====")

df10.columns = df10.columns.str.strip()

# Handle datetime
if 'date' in df10.columns:
    df10['date'] = pd.to_datetime(df10['date'], errors='coerce')
    df10 = df10.sort_values('date')

# Drop weak rows
df10 = df10.dropna(thresh=int(0.7 * df10.shape[1]))

# Target
target10 = df10.columns[-1]

X10 = df10.drop(columns=[target10])
y10 = df10[target10]

# Convert comma decimals → numeric
X10 = X10.astype(str).replace(',', '.', regex=True)
X10 = X10.apply(pd.to_numeric, errors='coerce')
X10 = X10.dropna(axis=1, how='all')
X10 = X10.fillna(X10.mean())

y10 = y10.astype(str).str.replace(',', '.')
y10 = pd.to_numeric(y10, errors='coerce')
y10 = y10.fillna(y10.mean())

# Split
X_train10, X_test10, y_train10, y_test10 = train_test_split(
    X10, y10, test_size=0.2, random_state=42
)

# Scale
scaler10 = StandardScaler()
X_train10 = scaler10.fit_transform(X_train10)
X_test10 = scaler10.transform(X_test10)

# Model
model10 = RandomForestRegressor(n_estimators=150, max_depth=10, random_state=42)
model10.fit(X_train10, y_train10)

# Predict
y_pred10 = model10.predict(X_test10)

# Evaluation
print("\n--- Mining Results ---")
print("MAE:", mean_absolute_error(y_test10, y_pred10))
print("R2 Score:", r2_score(y_test10, y_pred10))
print("RMSE:", np.sqrt(mean_squared_error(y_test10, y_pred10)))

# Scatter Plot
plt.figure()
plt.scatter(y_test10, y_pred10)
plt.xlabel("Actual Silica")
plt.ylabel("Predicted Silica")
plt.title("Mining Prediction")
plt.show()

# Trend Plot (Bonus)
plt.figure()
plt.plot(y_test10.values[:100], label="Actual")
plt.plot(y_pred10[:100], label="Predicted")
plt.legend()
plt.title("Mining Trend Comparison")
plt.show()

# Project 11: Multi-stage continuous-flow manufacturing process
''' Data set Link:
 https://drive.google.com/file/d/1yvZzslpbWw2mpCVF5QqueSkNrNHmtvDE/view?usp=share_link'''

print("\n===== PROJECT 11: Manufacturing =====")

df11.columns = df11.columns.str.strip()

df11 = df11.dropna(thresh=int(0.7 * df11.shape[1]))

target11 = df11.columns[-1]

X11 = df11.drop(columns=[target11])
y11 = df11[target11]

# Convert comma decimals → numeric
X11 = X11.astype(str).replace(',', '.', regex=True)
X11 = X11.apply(pd.to_numeric, errors='coerce')
X11 = X11.dropna(axis=1, how='all')
X11 = X11.fillna(X11.mean())

y11 = y11.astype(str).str.replace(',', '.')
y11 = pd.to_numeric(y11, errors='coerce')
y11 = y11.fillna(y11.mean())

# Split
X_train11, X_test11, y_train11, y_test11 = train_test_split(
    X11, y11, test_size=0.2, random_state=42
)

# Scale
scaler11 = StandardScaler()
X_train11 = scaler11.fit_transform(X_train11)
X_test11 = scaler11.transform(X_test11)

# Model
model11 = RandomForestRegressor(n_estimators=150, max_depth=12, random_state=42)
model11.fit(X_train11, y_train11)

# Predict
y_pred11 = model11.predict(X_test11)

# Evaluation
print("\n--- Manufacturing Results ---")
print("MAE:", mean_absolute_error(y_test11, y_pred11))
print("R2 Score:", r2_score(y_test11, y_pred11))
print("RMSE:", np.sqrt(mean_squared_error(y_test11, y_pred11)))

# Scatter Plot
plt.figure()
plt.scatter(y_test11, y_pred11)
plt.xlabel("Actual Output")
plt.ylabel("Predicted Output")
plt.title("Manufacturing Prediction")
plt.show()

# FEATURE IMPORTANCE
print("\n===== FEATURE IMPORTANCE (Mining) =====")

importances = model10.feature_importances_
features = X10.columns

plt.figure(figsize=(4,6))
plt.barh(features, importances)
plt.title("Feature Importance")
plt.show()

# FINAL MESSAGE
print("\n SUCCESS: Both Projects Completed Without Errors!")